@ECommerce_Api_HostAddress = https://localhost:7267

### Get API info
GET {{ECommerce_Api_HostAddress}}/api/system/info
Accept: application/json

### Echo route parameter only
GET {{ECommerce_Api_HostAddress}}/api/system/echo/hello
Accept: application/json

### Echo route parameter and query string
GET {{ECommerce_Api_HostAddress}}/api/system/echo/hello?name=Ali
Accept: application/json