name: Build .NET API

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          architecture: x64

      - name: Restore dependencies
        run: dotnet restore src/ECommerce.Api/ECommerce.Api.csproj

      - name: Build project
        run: dotnet build src/ECommerce.Api/ECommerce.Api.csproj --configuration Release --no-restore
